// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlibrary1;

@net.sf.jni4net.attributes.ClrType
public class Class1 extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Class1(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Class1() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlibrary1.Class1.__ctorClass10(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorClass10(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String GetName();
    
    public static system.Type typeof() {
        return classlibrary1.Class1.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlibrary1.Class1.staticType = staticType;
    }
    //</generated-proxy>
}
